angular.module('madLibsApp',[])
		.controller('dataController',function($scope){
			$scope.maleName="";
			$scope.dirtyTask="";
			$scope.obnoxiousCelebrity="";
			$scope.jobTitle="";
			$scope.celebrity="";
			$scope.hugeNumber="";
			$scope.tediousTask="";
			$scope.uselessSkill="";
			$scope.adjective="";
		});